Traceback (most recent call last):
  File "/home/rpi/GitHub-showcase/python-utils/tests/test_validators.py", line 6, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
